import Navbar from "@/components/app/Navbar";
import Infobar from "@/components/app/Infobar";
import Footer from "@/components/app/Footer";
import "./globals.css";
import { Raleway, Poppins } from "next/font/google";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-raleway",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-poppins",
});

export const metadata = {
  title: "SAFR-E-IMAN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html>
        <body lang="en" className={`${raleway.variable} ${poppins.variable}`}>
          <Infobar />
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </>
  );
}
